version: "3.8"

services:
  web:
    build: .
    ports:
      - "${APP_PORT:-80}:8000"
    environment:
      - ENV=development
    env_file:
      - ${ENV_FILE:-.env}
    # user: "${UID}:${GID}"
