version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the project directory for live reload in development
    environment:
      - ENV=development
    env_file:
      - ${ENV_FILE:-.env}
    user: "${UID}:${GID}"
